name: Taggercli

defaults:
  run:
    working-directory: "taggercli"
on:
  push:
    paths:
      - 'taggercli/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Validate style with black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "taggercli --check"
      - name: Test with tox
        run: tox

      - name: Upload to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: taggercli/coverage.xml
          flags: taggercli
          fail_ci_if_error: true
